#! /bin/bash

##
#/
#/ @PROGRAM@ can be used to book the first lunch appearing in a JSON
#/ list of meals returned by list-available-lunches.
#/
#/ Usage:
#/
#/ list-available-lunches | filter-lunches FILTERS | @PROGRAM@
#/
##

where_am_i="${0%/*}"
source "${where_am_i}/common"

while getopts "h" option_name; do
    case $option_name in
        h) usage;;
    esac
done

lunch_id=$(jq '.[0].id') ||
    die "No lunch passed in input"

[[ "${lunch_id}" != "null" ]] ||
    die "No lunch passed in input."

call_api 'https://secure.mealpal.com/api/v2/reservations' --data-binary \
'{"quantity":1,"schedule_id":'"${lunch_id}"\
',"pickup_time":"12:15pm-12:30pm","source_attributes":'\
'{"location":"kitchen_meal_view","platform":"web"}}' | jq '.' ||
    die "Failed to book lunch '${lunch_id}'"
