#! /bin/bash

##
#/
#/ Really basic alternative to cron jobs to make it easier to use for anyone.
#/ If the date specified is in the past, returns directly.
#/ Another alternative would be to use the command 'at':
#/   echo "ps aux > /tmp/file" | at 08:58
#/
#/ Usage:
#/
#/ @PROGRAM@ -d <date>
#/
#/      -d <date> Sleep until date (e.g. -d '2018/08/29 17:00:00')
#/
##

where_am_i="${0%/*}"
source "${where_am_i}/common"

date_in=""
while getopts "hd:" option_name; do
    case $option_name in
        d) date_in="${OPTARG:-}";;
        h) usage;;
    esac
done

[[ -n "${date_in}" ]] || usage "No date specified in input."

current_epoch=$(date +%s)
target_epoch=$(date -d "${date_in}" +%s)

sleep_seconds=$(( $target_epoch - $current_epoch ))

if [[ ${sleep_seconds} -gt 0 ]]; then
    sleep ${sleep_seconds}
fi
